<?php
/**
 * Wing
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 * @category    Wing Mod
 * @package     Shipox_Delivery
 * @author      Wing Delivery Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.shipox.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Shipox_Delivery_Block_Adminhtml_System_Config_Form_GetTokenButton
 */
?>

<?php echo $this->getButtonHtml();

?>
<script type="text/javascript">
    //<![CDATA[
    function getJWTToken() {
        var $params = {
            username: document.getElementById("shipox_delivery_auth_user_name").value,
            password: document.getElementById("shipox_delivery_auth_password").value
        };

        new Ajax.Request('<?php echo $this->getAjaxGetTokenUrl() ?>', {
            parameters: $params,
            onSuccess: function (transport) {
                console.log(transport);
                if (transport.responseText) {
                    var response = transport.responseText.evalJSON(true);
                    if (response.status) {
                        window.location.reload();
                    } else {
                        alert(response.description);
                    }
                }
            }
        });
    }
    //]]>
</script>