<?php

$trackerModel = new Shipox_Delivery_Model_Tracking();
$helper = new Shipox_Delivery_Helper_Data();

$shipoxTrackOrder = $trackerModel->getOrderTrackingData($this->getOrder());

if($shipoxTrackOrder) :
    $orderURL = $helper->getWingSiteURL()."/track/".$shipoxTrackOrder['wing_order_number'];
    ?>
    <div class="col1-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipox Delivery') ?></h2>
                </div>
                <div class="box-content">
                    <p>Shipox Shipment Tracking ID: <a href="<?php echo $orderURL; ?>" target="_blank">#<?php echo $shipoxTrackOrder['wing_order_number']; ?></a></p>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
<?php endif; ?>
