<?php
    $shipoxTrackOrder = $this->trackOrder();
    if($shipoxTrackOrder) {
        ?>
        <div class="field">
            <h2 class='subtitle'><?php echo Mage::getStoreConfig('shipox_delivery/service/title'); ?></h2>
            Your order will be shipped by <a href="<?php echo Mage::getStoreConfig('shipox_delivery/service/site_url'); ?>" target="_blank">shipox.com</a>. Your tracking ID is #<?php echo $shipoxTrackOrder['wing_order_number']; ?>. Your shipment can be tracked <a href="<?php echo $shipoxTrackOrder['wing_order_url']; ?>" target="_blank" title="Track Shipox Order URL"><strong>here</strong></a>
        </div>
        <?php
    }
?>
